### PR TITLE
Fix user query when using libc implementation of os/user

### LINKED ISSUE #191: Panic with "unknown userid" and "runtime error: invalid memory address or nil pointer dereference"
I installed `lf` through nix on gLinux, which is a debian based distribution within Google. When I launched `lf`, it panic'ed and printed:

```
2019/06/24 14:45:28 user: user: unknown userid 674665
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x56b17f]

goroutine 1 [running]:
main.init.3()
        /build/source/os.go:71 +0x7df
```

It seems it was triggered by the `user.Current()` call on os.go:57. It might be an error only happens with gLinux, as gLinux use a different way to authenticate users, I couldn't find an entry of my user in /etc/passwd. I will try to dig it further when I have time. `ranger` worked fine through.

I'm not familiar with golang through, it seems `lf` only uses `gUser = user.Current()` to get HomeDir and UserName. It did have $HOME and $USER check around os.go:60, but it didn't use them. Maybe refactor `gUser` into `gHomeDir` and `gUserName`, and take the values from $HOME and $USER when `user.Current()` fails? Or at least fail on the spot rather than trigger a panic later on?

### PR DESCRIPTION
**Pull request by GaetanLepage**
Fixes #191 

In the case where the user is not in `/etc/passwd` (for e.g. LDAP), the cgo implementation of `os/user` which uses the `libc` functions is not able to find the user name and home directory.

This fix implements a fallback that uses the `$USER` and `$HOME` environment variables.

Note: This problem does not occur when using the pure go implementation of `os/user` (for e.g. when specifying `CGO_ENABLED=0`) which already implements the same kind of fallback.

### CODE REVIEW

File: os.go [hunk 1]
```diff
@@ -66,10 +66,14 @@ func init() {
 	if err != nil {
 		log.Printf("user: %s", err)
```
Comment (ilyagr) [inline os.go:67]: Could you add a comment here, something along the lines:

// When the user is not in `/etc/passwd` (for e.g. LDAP) and `CGO_ENABLED=1` in `go env`,
// the cgo implementation of `user.Current()` fails even when HOME and USER are set.

Comment (GaetanLepage) [reply os.go:70]: Done !

**Comment by gokcehan** [comment]
@GaetanLepage Thanks for the patch.
