### PR TITLE
fix: prevent following symlinks for `cd`

### LINKED ISSUE #2422: cd changes directory to realpath instead of verbatim path
When using cd command to change into a directory path containing symbolic links, the links are resolved so the resulting path is realpath.

How to reproduce:
```bash
mkdir dir
ln -s dir dir-link
lf
:cd dir-link
```
Current directory is `dir`.

Version: r41
OS: Linux

### PR DESCRIPTION
**Pull request by joelim-work**
- Fixes #2422 

Limit the use of [`os.Getwd`](https://pkg.go.dev/os#Getwd), which can resolve symbolic links.

> Getwd returns an absolute path name corresponding to the current directory. If the current directory can be reached via multiple paths (due to symbolic links), Getwd may return any one of them.

Instead, where possible, the internal state (e.g. `app.nav.currDir().path`) should be used to get the current directory.

### CODE REVIEW

File: app.go [hunk 1]
```diff
@@ -296,7 +296,6 @@ func (app *app) loop() {
 		}
 	}
 
-	app.nav.loadDirs()
```
Comment (joelim-work) [inline app.go:299]: No longer needed as the current directory will be loaded and added to the jump list in the next line of code.

File: app.go [hunk 2]
```diff
@@ -473,12 +472,7 @@ func (app *app) loop() {
 			}
 
 			deletePathRecursive(app.nav.regCache, path)
-
 			deletePathRecursive(app.nav.dirCache, path)
-			currPath := app.nav.currDir().path
-			if currPath == path || strings.HasPrefix(currPath, path+string(filepath.Separator)) {
-				app.nav.loadDirs()
-			}
```
Comment (joelim-work) [inline app.go:481]: The intention of this code was to deal with the situation where the current directory (or a parent) gets deleted externally while `watch` is enabled. The behavior is buggy so I am removing it.
